### ISSUE TITLE
ACNA-270 - access-token doesnt get a new token if one exists, even if the private key has changed

### ISSUE THREAD

**Issue by goya** [adobe/aio-cli-plugin-jwt-auth#29]
### Expected Behaviour
if the private key has changed then the access token should be regenerated

### Actual Behaviour
private key is not regenerated if it already exists

**Comment by shazron** [comment]
@goya is this related to #30? if not, it shouldn't be closed. I think I asked you if it was related you said it wasn't (in Slack)

**Comment by shazron** [comment]
Solved in #33
