### ISSUE TITLE
Remove aio-cli-plugin-jwt-auth from CLI Core plugins and deprecate

### ISSUE THREAD

**Issue by meryllblanchet** [adobe/aio-cli-plugin-jwt-auth#86]
We recently enhanced the CLI and SDK with OAuth2 and JWT support through:

- Library based IMS integration: https://github.com/adobe/aio-lib-ims
- Authentication plugin: https://github.com/adobe/aio-cli-plugin-auth

This plugin is then obsolete. Could we

1) Remove it from CLI Core
2) Deprecate it?

**Comment by shazron** [comment]
done for both https://www.npmjs.com/package/@adobe/aio-cli-plugin-jwt-auth
